#!/bin/bash -xv
# 感谢原作者老徐 源代码主页：https://github.com/the0demiurge
# 输入ssr config进行配置，输入JSON格式的配置文件
# 默认配置文件位于: /usr/local/share/shadowsocksr/config.json
# ssr start可以指定 -c config.json
# 输入ssr uninstall卸载
# 输入ssr help 显示帮助信息


set -e
if [ -z $EDITOR ];then
    EDITOR=vi
fi

help() {
    echo ShadowSocksR python client tool
    echo -e if you have not install ssr, please run \"ssr install\"
    echo Usage:
    echo -e "\t" ssr help
    echo -e "\t" ssr config : edit config.json
    echo -e "\t" ssr install : install shadowsocksr client
    echo -e "\t" ssr uninstall : uninstall shadowsocksr client
    echo -e "\t" ssr start : start the shadowsocks service
    echo -e "\t" ssr stop : stop the shadowsocks service
    echo -e "\t" ssr log : cat the log of shadowsocks
}

install_path=/usr/local/share/shadowsocksr
if [ $# == 0 ];then
    help
    
elif [ $1 == "help" ];then
    help
    
elif [ $1 == "install" ];then
    git clone -b manyuser https://github.com/shadowsocksr-backup/shadowsocksr.git $install_path
    # sudo git clone -b rm https://github.com/the0demiurge/not-in-use.git $install_path
    
elif [ $1 == "uninstall" ];then
    echo "Danger! are you to remove $install_path forever?(y/N)"
    read doit
    if [ $doit == 'y' ];then
        echo "Uninstall ssr-client!" 
        sudo rm -rvf $install_path
    else
        echo "Not to uninstall ssr-client."
    fi
    
elif [ $1 == "config" ];then
    sudo $EDITOR $install_path/config.json

# add params for shadowsocksr/local.py
# author: peerless1230
elif [ $1 == "start" ];then
    basepath=$(cd `dirname $0`; pwd)
    cd $install_path/shadowsocks/
    arr=$@
    flag=0
    for i in ${!arr[@]}
    do  
        if "$flag" -eq "1"; then
            arr[$i] = $basepath${arr[$i]}
        elif "${arr[$i]}" -eq "-c"; then
            flag=1
        fi
    done
    arr=${arr/start -c /-c $basepath\/}
    echo $@
    echo $arr
    sudo python local.py -d stop
    sudo python local.py $arr -d start
 
elif [ $1 == "stop" ];then
    cd $install_path/shadowsocks/
    sudo python local.py -d stop
    
elif [ $1 == "log" ];then
    tail -f /var/log/shadowsocks.log
    
elif [ $1 == "shell" ];then
    cd $install_path/shadowsocks/
    sudo python local.py $@
fi
